# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
flipbook-cli = "flipbook-labs/flipbook-cli@0.6.0"
git-cliff = "orhun/git-cliff@2.13.1"
